on:
    workflow_call:
        secrets:
            ssh-private-key:
                required: false

jobs:
    coding_standards:
        name: "Run checks"
        runs-on: "ubuntu-20.04"

        env:
            ssh-private-key: ${{ secrets.ssh-private-key }}

        strategy:
            matrix:
                php-version:
                    - "7.4"
                dependency-versions:
                    - "highest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"
                  tools: "cs2pr"

            - name: "Install SSH key for private libraries"
              if: "${{ env.ssh-private-key }}"
              uses: "webfactory/ssh-agent@v0.5.4"
              with:
                  ssh-private-key: "${{ secrets.ssh-private-key }}"

            - name: "Install Composer dependencies"
              uses: "ramsey/composer-install@v2"
              with:
                  dependency-versions: "${{ matrix.dependency-versions }}"

            - name: "PHP CS Fixer"
              run: "composer run-script tools:php-cs-fixer-dry-run"
