on:
    workflow_call:
        inputs:
            php-version:
                description: "The PHP version to use when running the job"
                default: "7.4"
                required: false
                type: "string"
        secrets:
            composer-token:
                required: false
                description: "Personal access token to authenticate for private repositories"

jobs:
    coding_standards:
        name: "Run checks"
        runs-on: "ubuntu-20.04"

        strategy:
            matrix:
                php-version:
                    - "${{ inputs.php-version }}"
                dependency-versions:
                    - "highest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v3"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    php-version: "${{ matrix.php-version }}"
                    tools: "cs2pr, symfony-cli"
                    extensions: "ctype, gd, iconv, intl, mbstring, pdo_sqlite, json"
                env:
                    # When composer-token is not available, use GITHUB_TOKEN to prevent rate limit errors (https://github.com/actions/runner/issues/409)
                    COMPOSER_TOKEN: ${{ secrets.composer-token || secrets.GITHUB_TOKEN }}

            -   name: "Install Composer dependencies"
                uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: "${{ matrix.dependency-versions }}"

            -   name: "PHP CS Fixer"
                run: "make php-cs-fixer-dry-run"
